# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the bash branch
  push:
    tags: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # Runs a set of commands using the runners shell
      - name: download files
        run: |
          wget https://sourceforge.net/projects/ssh-pull-id/files/ssh-pull-id.tar.gz
          tar -xf ssh-pull-id.tar.gz
          rm ssh-pull-id.tar.gz

      - name: zip it
        uses: tuxecure/zip-it@v2.1
        with:
          pkg_directories: bin
          bin: ssh-pull-id
          owner: tuxecure
          package_name: ssh-pull-id

      - name: setup release
        uses: spenserblack/actions-tag-to-release@master

      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          files: ssh-pull-id.zip
